test_task:
  container:
    matrix:
      - image: erlang:24
      - image: erlang:23
      - image: erlang:22
      - image: erlang:21
      - image: erlang:20
      - image: erlang:19
  rebar3_cache:
    folder: _build
    fingerprint_script: cat rebar.lock
    populate_script: rebar3 compile --deps_only
  compile_script: rebar3 compile
  test_script: rebar3 ct
