%%%-------------------------------------------------------------------
%%% Local macro discovery sees forms generated by an earlier external pass.
%%%-------------------------------------------------------------------
-module(macro_pass_external_local_helper_test).

-include("macro.hrl").

-export([value/0]).

-import_macro(macro_pass_external_helper).
-generate_helper(ok).

-local_macro([entry/0]).

value() ->
    entry().

entry() ->
    generated_helper().
