%%%-------------------------------------------------------------------
%%% Local attribute macros generated by local attribute macros are expanded.
%%%-------------------------------------------------------------------
-module(macro_pass_local_chain_test).

-include("macro.hrl").

-export([local_chain_value/0]).

-local_macro({[gen_first/1, gen_second/1], [as_attr]}).

-gen_first(ok).

gen_first(_Ast) ->
    astranaut_lib:gen_attribute_node(gen_second, 0, ok).

gen_second(_Ast) ->
    astranaut_lib:gen_function(local_chain_value,
                               astranaut_lib:abstract_form({local_attribute_chain, ok})).
