%%%-------------------------------------------------------------------
%%% @doc Source-ordered macro attribute scan-and-splice.
%%%
%%% This module owns the scan queue, passed/remaining source views and the
%%% traverse state used while attributes are processed. Macro declarations
%%% and environments are delegated to astranaut_macro_registry.
%%% @end
%%%-------------------------------------------------------------------

-module(astranaut_macro_scan).

-include("do.hrl").

-export([run/5, run/6, map_forms_splice/3]).

-type fa() :: {atom(), non_neg_integer()}.
-type scanner_state() ::
        #{module := module(),
          file := term(),
          compile_opts := [compile:option()],
          registry := astranaut_macro_registry:state(),
          passed_forms := [term()],
          local_macro_state := map(),
          local_declarations := #{term() => {term(), [fa()]}},
          attribute_expansion =>
              #{count := non_neg_integer(),
                max_depth := non_neg_integer(),
                origin := map()},
          remaining_forms => [term()]}.

%%%===================================================================
%%% Public API
%%%===================================================================

-spec run(module(), file:filename(), map(), [term()], [compile:option()]) ->
          astranaut_return:struct({[term()], scanner_state()}).
run(Module, File, GlobalMacroOpts, Forms, CompileOpts) ->
    run(Module, astranaut_macro_local:module_name(Module), File,
        GlobalMacroOpts, Forms, CompileOpts).

-spec run(module(), module(), file:filename(), map(), [term()],
          [compile:option()]) ->
          astranaut_return:struct({[term()], scanner_state()}).
run(Module, LocalMacroModule, File, GlobalMacroOpts, Forms, CompileOpts) ->
    InitState =
        #{module => Module,
          file => File,
          compile_opts => CompileOpts,
          registry => astranaut_macro_registry:new(
                        Module, LocalMacroModule, File, GlobalMacroOpts),
          passed_forms => [],
          local_macro_state => astranaut_macro_local:new(LocalMacroModule),
          local_declarations => #{}},
    astranaut_traverse:run(
      map_forms_splice(
        fun scan_form/1, Forms,
        #{traverse => none, queue_state => true}),
      astranaut_macro,
      #{node => form, validator => {role, form}},
      InitState).

%% Macro-specific source queue. Rest owns the outer module continuation while
%% Buffer owns every form generated by one root attribute. Buffer is always
%% drained first, so its attribute expansions share one counter and generated
%% function/spec forms still reach the single final merge below.
map_forms_splice(F, Forms, Opts) ->
    map_forms_splice_loop(
      F, [{form, Form} || Form <- Forms], [], [], Opts).

%%%===================================================================
%%% Scan-and-splice queue
%%%===================================================================

map_forms_splice_loop(F, Rest, [{Tag, Form} | Buffer], Acc, Opts) ->
    map_forms_splice_form(
      F, {Tag, Form}, Rest, Buffer, Acc, buffer, Opts);
map_forms_splice_loop(F, [{Tag, Form} | Rest], [], Acc, Opts) ->
    astranaut_traverse:then(
      clear_map_forms_splice_buffer(),
      map_forms_splice_form(
        F, {Tag, Form}, Rest, [], Acc, rest, Opts));
map_forms_splice_loop(_F, [], [], Acc, _Opts) ->
    astranaut_traverse:then(
      clear_map_forms_splice_buffer(),
      astranaut_traverse:return(
        map_forms_splice_reorder(lists:reverse(Acc)))).

map_forms_splice_form(F, {Tag, Form}, Rest, Buffer, Acc, Location, Opts) ->
    Queue = [Form | map_forms_splice_untag(Buffer) ++
                    map_forms_splice_untag(Rest)],
    astranaut_traverse:bind(
      map_forms_splice_note_queue(Opts, Queue),
      fun(_) ->
              astranaut_traverse:bind(
                astranaut_traverse:catch_on_error(
                  astranaut:traverse_form(F, Form),
                  fun() ->
                          astranaut_traverse:return({splice, []})
                  end),
                fun(Result) ->
                        map_forms_splice_result(
                          Result, Tag, F, Rest, Buffer, Acc,
                          Location, Opts)
                end)
      end).

map_forms_splice_result(
    {buffer, NewForms, MaxDepth, Origin}, _Tag,
    F, Rest, _Buffer, Acc, rest, Opts) ->
    GeneratedForms =
        [map_forms_splice_tag_generated(NewForm) || NewForm <- NewForms],
    astranaut_traverse:then(
      astranaut_traverse:modify(
        fun(State) ->
                State#{attribute_expansion =>
                           #{count => 1,
                             max_depth => MaxDepth,
                             origin => Origin}}
        end),
      map_forms_splice_loop(F, Rest, GeneratedForms, Acc, Opts));
map_forms_splice_result(
    {splice, NewForms}, _Tag, F, Rest, Buffer, Acc, buffer, Opts) ->
    GeneratedForms =
        [map_forms_splice_tag_generated(NewForm) || NewForm <- NewForms],
    map_forms_splice_loop(
      F, Rest, GeneratedForms ++ Buffer, Acc, Opts);
map_forms_splice_result(
    {splice, NewForms}, _Tag, F, Rest, [], Acc, rest, Opts) ->
    GeneratedForms =
        [map_forms_splice_tag_generated(NewForm) || NewForm <- NewForms],
    map_forms_splice_loop(F, GeneratedForms ++ Rest, [], Acc, Opts);
map_forms_splice_result(
    Form1, Tag, F, Rest, Buffer, Acc, _Location, Opts) ->
    map_forms_splice_loop(
      F, Rest, Buffer,
      [map_forms_splice_tag_result(Tag, Form1) | Acc], Opts).

clear_map_forms_splice_buffer() ->
    astranaut_traverse:modify(
      fun(State) -> maps:remove(attribute_expansion, State) end).

map_forms_splice_note_queue(#{queue_state := true}, Queue) ->
    astranaut_traverse:modify(
      fun(State) -> State#{remaining_forms => Queue} end);
map_forms_splice_note_queue(_Opts, _Queue) ->
    astranaut_traverse:return(ok).

map_forms_splice_tag_generated(
    {function, _Pos, _Name, _Arity, _Clauses} = Form) ->
    {generated_insert, Form};
map_forms_splice_tag_generated(
    {attribute, _Pos, spec, _Spec} = Form) ->
    {generated_insert, Form};
map_forms_splice_tag_generated(Form) ->
    {form, Form}.

map_forms_splice_tag_result(
    generated_insert,
    {function, _Pos, _Name, _Arity, _Clauses} = Form) ->
    {generated_insert, Form};
map_forms_splice_tag_result(
    generated_insert,
    {attribute, _Pos, spec, _Spec} = Form) ->
    {generated_insert, Form};
map_forms_splice_tag_result(_Tag, Form) ->
    {form, Form}.

map_forms_splice_reorder(TaggedForms) ->
    TaggedForms1 = map_forms_splice_merge_specs(TaggedForms),
    map_forms_splice_reorder(TaggedForms1, []).

map_forms_splice_merge_specs(TaggedForms) ->
    MergeFAs = map_forms_splice_merge_fas(TaggedForms),
    GeneratedSpecFAs = ordsets:from_list(
      [FA || {generated_insert, Form} <- TaggedForms,
             FA <- [map_forms_splice_spec_fa(Form)],
             FA =/= undefined,
             ordsets:is_element(FA, MergeFAs)]),
    [Tagged || Tagged = {Tag, Form} <- TaggedForms,
               not (Tag =:= form andalso
                    ordsets:is_element(
                      map_forms_splice_spec_fa(Form),
                      GeneratedSpecFAs))].

map_forms_splice_merge_fas(TaggedForms) ->
    Forms = map_forms_splice_untag(TaggedForms),
    FunctionFAs =
        [{Name, Arity}
         || {function, _Pos, Name, Arity, _Clauses} <- Forms],
    ordsets:from_list(
      [{Name, Arity}
       || {generated_insert,
           {function, _Pos, Name, Arity, _Clauses} = Form} <- TaggedForms,
          map_forms_splice_is_renamed(Arity, Form),
          length([ok || FA <- FunctionFAs,
                        FA =:= {Name, Arity}]) > 1]).

map_forms_splice_spec_fa(
    {attribute, _Pos, spec, {{Name, Arity}, _Specs}}) ->
    {Name, Arity};
map_forms_splice_spec_fa(_Form) ->
    undefined.

map_forms_splice_reorder(
    [{generated_insert,
      {function, _Pos, Name, Arity, _Clauses} = Form} | T], Acc) ->
    case map_forms_splice_needs_merge(Name, Arity, Form, Acc, T) of
        true ->
            Functions = map_forms_splice_forms_functions(
                          lists:reverse(Acc) ++
                              [Form | map_forms_splice_untag(T)]),
            NewName = map_forms_splice_new_function_name(
                        Name, Arity, Functions),
            Form1 = map_forms_splice_update_call_name(
                      '__original__', NewName, Arity, Form),
            Acc1 = map_forms_splice_update_function_name(
                     Name, Arity, NewName, Acc),
            T1 = map_forms_splice_update_tagged_function_name(
                   Name, Arity, NewName, T),
            map_forms_splice_reorder(T1, [Form1 | Acc1]);
        false ->
            map_forms_splice_reorder(T, [Form | Acc])
    end;
map_forms_splice_reorder([{_Tag, Form} | T], Acc) ->
    map_forms_splice_reorder(T, [Form | Acc]);
map_forms_splice_reorder([], Acc) ->
    lists:reverse(Acc).

map_forms_splice_needs_merge(Name, Arity, Form, Acc, T) ->
    map_forms_splice_is_renamed(Arity, Form) andalso
        ordsets:is_element(
          {Name, Arity},
          map_forms_splice_forms_functions(
            lists:reverse(Acc) ++ map_forms_splice_untag(T))).

map_forms_splice_untag(TaggedForms) ->
    [Form || {_Tag, Form} <- TaggedForms].

map_forms_splice_forms_functions(Forms) ->
    lists:foldl(
      fun({function, _Pos, Name, Arity, _Clauses}, Acc) ->
              ordsets:add_element({Name, Arity}, Acc);
         (_Form, Acc) ->
              Acc
      end, ordsets:new(), Forms).

map_forms_splice_is_renamed(Arity, Form) ->
    astranaut:search(
      fun({call, _Pos1, {atom, _Pos2, '__original__'}, Arguments}) ->
              length(Arguments) =:= Arity;
         (_Node) ->
              false
      end, Form, #{traverse => pre}).

map_forms_splice_new_function_name(FName, Arity, Functions) ->
    map_forms_splice_new_function_name(FName, Arity, Functions, 1).

map_forms_splice_new_function_name(FName, Arity, Functions, Counter) ->
    FName1 = list_to_atom(
               atom_to_list(FName) ++ "_" ++ integer_to_list(Counter)),
    case ordsets:is_element({FName1, Arity}, Functions) of
        true ->
            map_forms_splice_new_function_name(
              FName, Arity, Functions, Counter + 1);
        false ->
            FName1
    end.

map_forms_splice_update_tagged_function_name(
    Name, Arity, NewName, TaggedForms) ->
    [{Tag,
      map_forms_splice_update_function_name_1(
        Name, Arity, NewName, Form)}
     || {Tag, Form} <- TaggedForms].

map_forms_splice_update_function_name(Name, Arity, NewName, Forms) ->
    [map_forms_splice_update_function_name_1(
       Name, Arity, NewName, Form)
     || Form <- Forms].

map_forms_splice_update_function_name_1(
    Name, Arity, NewName,
    {function, Pos, FName, FArity, Clauses})
  when FName =:= Name, FArity =:= Arity ->
    Clauses1 = map_forms_splice_update_call_name(
                 Name, NewName, Arity, Clauses),
    {function, Pos, NewName, Arity, Clauses1};
map_forms_splice_update_function_name_1(
    _Name, _Arity, _NewName, Form) ->
    Form.

map_forms_splice_update_call_name(
    OriginalName, NewName, Arity, Function) ->
    astranaut:smap(
      fun({call, Pos, {atom, Pos2, Name}, Arguments})
            when Name =:= OriginalName, length(Arguments) =:= Arity ->
              {call, Pos, {atom, Pos2, NewName}, Arguments};
         (Node) ->
              Node
      end, Function, #{traverse => pre}).

%%%===================================================================
%%% Form handlers
%%%===================================================================

scan_form(Form) ->
    do([ traverse ||
           State <- astranaut_traverse:get(),
           case Form of
               {attribute, _Pos, local_macro, _Attr} ->
                   scan_local_macro(Form, State);
               {attribute, _Pos, import_macro, _Attr} ->
                   scan_env_form(Form, State);
               {attribute, _Pos, use_macro, _Attr} ->
                   scan_env_form(Form, State);
               {attribute, _Pos, macro_options, _Attr} ->
                   scan_env_form(Form, State);
               _ ->
                   scan_attribute_runtime(Form, State)
           end
       ]).

scan_local_macro(
  {attribute, Pos, local_macro, Attr} = Form,
  #{registry := Registry,
    local_macro_state := LocalState,
    local_declarations := LocalDeclarations} = State) ->
    Queue = remaining_source_forms(State),
    SourceView = astranaut_macro_local:source_view(
                   passed_forms(State), Queue),
    ClauseMap = function_clauses_map(SourceView, #{}),
    Validation = astranaut_macro_registry:validate_local_macro_attribute(
                   ClauseMap, Attr),
    case astranaut_return:run(Validation) of
        {just, {FAs, Options}} ->
            do([ traverse ||
                   astranaut:traverse_return(Validation),
                   scan_valid_local_macro(
                     Form, Pos, FAs, Options, ClauseMap,
                     SourceView, State, Registry, LocalState,
                     LocalDeclarations)
               ]);
        nothing ->
            astranaut:traverse_return(Validation)
    end.

scan_valid_local_macro(
  Form, Pos, FAs, Options, ClauseMap, SourceView,
  State, Registry, LocalState, LocalDeclarations) ->
    do([ traverse ||
           RegisteredLocalState <- register_local_declaration(
                                     FAs, Options, Pos, SourceView,
                                     astranaut_macro_registry:
                                       declaration_macro_environment(
                                         Registry),
                                     LocalState),
           WorkflowContext = local_macro_workflow_context(
                               SourceView,
                               maps:get(compile_opts, State)),
           LocalState1 <- astranaut:traverse_return(
                            astranaut_macro_local:prepare_declaration(
                              FAs, WorkflowContext,
                              RegisteredLocalState)),
           Registry1 <- astranaut:traverse_return(
                          astranaut_macro_registry:add_local_macro(
                            FAs, Options, ClauseMap, Registry)),
           astranaut_traverse:put(
             note_passed_form(
               Form,
               State#{registry => Registry1,
                      local_macro_state => LocalState1,
                      local_declarations =>
                          maps:put(Form, {Pos, FAs},
                                   LocalDeclarations)})),
           return(Form)
       ]).

register_local_declaration(
  FAs, Options, Pos, SourceView, MacroEnvironment, LocalState) ->
    case astranaut_macro_local:register(
           FAs, Options, SourceView, MacroEnvironment, LocalState) of
        {ok, LocalState1} ->
            astranaut_traverse:return(LocalState1);
        {error, Error} ->
            astranaut_traverse:update_pos(
              Pos, astranaut_macro,
              astranaut_traverse:fail(Error))
    end.

scan_env_form(Form, #{registry := Registry} = State) ->
    do([ traverse ||
           {Action, Registry1} <- astranaut:traverse_return(
                                    astranaut_macro_registry:
                                      apply_directive(Form, Registry)),
           State1 = State#{registry => Registry1},
           case Action of
               consume ->
                   do([ traverse ||
                          astranaut_traverse:put(State1),
                          return({splice, []})
                      ]);
               keep ->
                   do([ traverse ||
                          astranaut_traverse:put(
                            note_passed_form(Form, State1)),
                          return(Form)
                      ])
           end
       ]).

scan_attribute_runtime(
  {attribute, _Pos, _Name, _Value} = Form,
  #{registry := Registry} = State) ->
    MacroMap = astranaut_macro_registry:effective_macro_map(Registry),
    AttributeIndex =
        astranaut_macro_registry:attribute_macro_index(Registry),
    case astranaut_macro_expander:resolve_attribute_target(
           Form, MacroMap, AttributeIndex) of
        {ok, Target0} ->
            Target = astranaut_macro_registry:resolve_attribute_target(
                       Target0, Registry),
            run_attribute_macro(Target, State);
        error ->
            do([ traverse ||
                   astranaut_traverse:warning(invalid_macro_attribute),
                   keep_scanned_form(Form)
               ]);
        not_macro ->
            keep_scanned_form(Form)
    end;
scan_attribute_runtime(Form, _State) ->
    keep_scanned_form(Form).

%%%===================================================================
%%% Attribute macro runtime
%%%===================================================================

run_attribute_macro(Target, State) ->
    case maps:find(attribute_expansion, State) of
        error ->
            run_root_attribute_macro(Target, State);
        {ok, Expansion} ->
            run_buffered_attribute_macro(Target, Expansion, State)
    end.

run_root_attribute_macro(Target, State) ->
    Macro = maps:get(macro, Target),
    MaxDepth = maps:get(max_depth, Macro, 100),
    case MaxDepth > 0 of
        false ->
            astranaut_traverse:fail(
              attribute_expansion_limit_error(Target));
        true ->
            do([ traverse ||
                   State1 <- ensure_attribute_target_callable(
                               Target, State),
                   Expanded <-
                       astranaut_macro_expander:expand_attribute_target(
                         Target),
                   ExpandedForms = to_list(Expanded),
                   assert_scan_frozen_forms(
                     ExpandedForms,
                     maps:get(local_macro_state, State1)),
                   return({buffer, ExpandedForms, MaxDepth, Target})
               ])
    end.

run_buffered_attribute_macro(
    _Target,
    #{count := Count, max_depth := MaxDepth} = Expansion,
    _State) when Count >= MaxDepth ->
    astranaut_traverse:fail(
      attribute_expansion_limit_error(maps:get(origin, Expansion)));
run_buffered_attribute_macro(
    Target, #{count := Count} = Expansion, State) ->
    do([ traverse ||
           State1 <- ensure_attribute_target_callable(Target, State),
           Expanded <- astranaut_macro_expander:expand_attribute_target(
                         Target),
           ExpandedForms = to_list(Expanded),
           assert_scan_frozen_forms(
             ExpandedForms, maps:get(local_macro_state, State1)),
           astranaut_traverse:put(
             State1#{attribute_expansion =>
                         Expansion#{count => Count + 1}}),
           return({splice, ExpandedForms})
       ]).

attribute_expansion_limit_error(
    #{macro := Macro, raw_arguments := Arguments}) ->
    {max_macro_expansion_depth_exceeded,
     maps:get(macro, Macro), Arguments}.

ensure_attribute_target_callable(
    #{macro := #{macro_source := local_macro,
                 function := Function, arity := Arity}},
    #{local_macro_state := LocalState,
      compile_opts := CompileOpts} = State) ->
    Queue = remaining_source_forms(State),
    case maps:find(
           {Function, Arity},
           astranaut_macro_local:local_macros(LocalState)) of
        {ok, #{status := compiled}} ->
            astranaut_traverse:return(State);
        {ok, _} ->
            SourceView = astranaut_macro_local:source_view(
                           passed_forms(State), Queue),
            do([ traverse ||
                   WorkflowContext = local_macro_workflow_context(
                                       SourceView, CompileOpts),
                   LocalState1 <- astranaut:traverse_return(
                                    astranaut_macro_local:need_callable(
                                      {Function, Arity},
                                      WorkflowContext, LocalState)),
                   State1 = State#{local_macro_state => LocalState1},
                   astranaut_traverse:put(State1),
                   return(State1)
               ]);
        error ->
            astranaut_traverse:return(State)
    end;
ensure_attribute_target_callable(_ExternalTarget, State) ->
    astranaut_traverse:return(State).

assert_scan_frozen_forms(Forms, LocalState) ->
    case astranaut_macro_local:reject_locked_mutation(
           Forms, LocalState) of
        ok ->
            astranaut_traverse:return(ok);
        {error, {illegal_locked_form_mutation, Form} = Error} ->
            astranaut_traverse:update_pos(
              form_pos(Form), astranaut_macro,
              astranaut_traverse:fail(Error))
    end.

%%%===================================================================
%%% Scan state helpers
%%%===================================================================

keep_scanned_form(Form) ->
    do([ traverse ||
           State <- astranaut_traverse:get(),
           astranaut_traverse:put(note_passed_form(Form, State)),
           return(Form)
       ]).

note_passed_form(
  Form,
  #{passed_forms := PassedForms,
    registry := Registry} = State) ->
    State#{passed_forms => [Form | PassedForms],
           registry => astranaut_macro_registry:note_form(
                         Form, Registry)}.

passed_forms(#{passed_forms := PassedForms}) ->
    lists:reverse(PassedForms).

remaining_source_forms(State) ->
    maps:get(remaining_forms, State, []).

form_pos({attribute, Pos, _Name, _Value}) -> Pos;
form_pos(_Form) -> 0.

local_macro_workflow_context(SourceView, CompileOpts) ->
    #{source_view => SourceView,
      compile_opts => CompileOpts}.

function_clauses_map(
  [{function, _Pos, Name, Arity, Clauses} | T], Acc) ->
    function_clauses_map(
      T, maps:put({Name, Arity}, Clauses, Acc));
function_clauses_map([_H | T], Acc) ->
    function_clauses_map(T, Acc);
function_clauses_map([], Acc) ->
    Acc.

to_list(Arguments) when is_list(Arguments) -> Arguments;
to_list(Arguments) -> [Arguments].
